### ISSUE TITLE
How do I actually get this running? 

### ISSUE THREAD

**Issue by samwisethelanky** [Crypto-AI/Gemini#3]
Hey, 

Cloned your Gemini git repo, tried running example.py but getting errors, like name gemini is not defined, so I put it in the same folder as gemini, imported gemini, now helpers has no attribute "getSignals".

**Comment by anfederico** [comment]
The example code won't run as is. You'll need to provide your own signal function(s) to generate signals in the data you provide. Gemini is strictly a backtesting engine, you'll need to provide data/signals.

**Comment by samwisethelanky** [comment]
Ahh I see, thanks.
